#!/bin/sh

compose_files=${compose_files:-$1}
target_version=${target_version:-${2:-"main"}}
quiet=${quiet:-${3:-0}}
environment=${environment:-$4}
project=${project:-${5:-nuvlaedge}}
github_releases=${github_releases:-${6:-"https://github.com/nuvlaedge/deployment/releases"}}
save_dir=${save_dir:-${7:-$(pwd)}}

export COMPOSE_PROJECT_NAME="${project}"

nuvlaedge-printer "Installing NuvlaEdge Engine to version: ${target_version}" ${quiet} "NONE" yes

if [[ ! -z "${environment}" ]]
then
  env_file="${save_dir}/.env"
  nuvlaedge-printer "Setting environment for install, at ${env_file}" ${quiet} "INFO" "no"

  env_lines=$(echo ${environment} | sed 's/,/\\n/g')
  nuvlaedge-printer "Environment variables:\n${env_lines}" ${quiet} "DEBUG" "no"

  echo -e "${env_lines}" > ${env_file}

  if [[ $? -ne 0 ]]
  then
    nuvlaedge-printer "Install failed! Unable to store enviroment ${env_lines} in ${env_file}." 0 "ERROR" "no"
    exit 1
  fi
fi

if [[ ! -z ${target_version} ]] && [[ "${target_version}" != "master" ]] && [[ "${target_version}" != "main" ]]
then
  # First, try downloading compose files from Nuvla
  nuvlaedge-printer "Downloading compose files ${compose_files} from Nuvla for version ${target_version}" ${quiet} "INFO" "no"

  download=$(nuvlaedge-download-nuvla-configs "${compose_files}" "${save_dir}" "${target_version}" 2>&1)

  # If fails, try Github release assets
  if [[ $? -ne 0 ]]
  then
    nuvlaedge-printer "Failed downloading compose files from Nuvla: ${download}" 0 "WARNING" "no"

    source_code_url="${github_releases}/download/${target_version}"

    nuvlaedge-printer "Downloading compose files ${compose_files} from ${source_code_url}" ${quiet} "INFO" "no"

    download=$(nuvlaedge-download-configs "${compose_files}" "${save_dir}" "${source_code_url}" 2>&1)

    if [[ $? -ne 0 ]]
    then
      nuvlaedge-printer "Install failed! Unable to retrieve compose files ${compose_files} from ${source_code_url}: ${download}" 0 "ERROR" "no"
      exit 1
    fi
  fi
fi

nuvlaedge-printer "Preparing to install NuvlaEdge Engine running as project ${project}" ${quiet} "NONE" "yes"

docker_compose_args=$(echo "-f $(echo ${compose_files} | sed 's/,/ -f /g')")
docker_compose_command="docker --log-level ERROR compose --ansi never -p ${project} ${docker_compose_args} up -d"

nuvlaedge-printer "Executing install command: ${docker_compose_command}" ${quiet} "INFO" "no"

if [[ ${quiet} -eq 1 ]]
then
  out=$($docker_compose_command 2>&1)
else
  out="\n$($docker_compose_command)"
fi

if [[ $? -ne 0 ]]
then
  nuvlaedge-printer "Install failed when executing Docker Compose command ${docker_compose_command}.${out}" 0 "ERROR" "no"
  exit 1
fi

wait=5
nuvlaedge-printer "Waiting ${wait} seconds and then checking NuvlaEdge Engine health..." ${quiet} "INFO" "no"
sleep ${wait}

# set timeout for 10 minutes
timer=600
nuvlaedge-printer "Checking NuvlaEdge Engine health (will timeout after ${timer} sec)..." ${quiet} "INFO" "no"
health=$(nuvlaedge-check-health ${timer} "${project}" 2>&1)

if [[ $? -ne 0 ]]
then
  nuvlaedge-printer "NuvlaEdge Engine is not healthy: ${health}" 0 "ERROR" "no"
  exit 1
fi

# if we got here, then install was successful
nuvlaedge-printer "NuvlaEdge Engine installed to version: ${target_version}!" 0 "" "no"
