apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment
  namespace: {{ include "nuvlabox-engine.namespace" . }}
  labels:
    {{- include "nuvlabox-engine.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      component: agent
  template:
    metadata:
      labels:
        component: agent
        {{- include "nuvlabox-engine.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.kubernetesNode }}
      containers:
        # AGENT
        - name: agent
          image: "{{ .Values.images.agent.repository }}:{{ .Values.images.agent.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.agent.pullPolicy }}
          securityContext:
            privileged: true
          env:
            - name: NUVLABOX_UUID
              value: {{ .Values.NUVLABOX_UUID }}
            - name: NUVLABOX_ENGINE_VERSION
              value: "2.0.0"
            - name: NUVLABOX_IMMUTABLE_SSH_PUB_KEY
              value: {{ .Values.NUVLABOX_IMMUTABLE_SSH_PUB_KEY }}
            - name: NUVLA_ENDPOINT
              value: {{ .Values.NUVLA_ENDPOINT | default "nuvla.io" | quote }}
            - name: NUVLA_ENDPOINT_INSECURE
              value: {{ .Values.NUVLA_ENDPOINT_INSECURE | default "False" | quote }}
            - name: NUVLABOX_JOB_ENGINE_LITE_IMAGE
              value: "{{ .Values.images.jobEngineLite.repository }}:{{ .Values.images.jobEngineLite.tag }}"
            - name: NUVLABOX_VPN_COMPONENT_NAME
              value: {{ .Values.vpnClientComponentName }}
            - name: HOST_HOME
              value: {{ .Values.HOME }}
            - name: VPN_INTERFACE_NAME
              value: {{ .Values.VPN_INTERFACE_NAME | default "vpn" | quote }}
            - name: MY_HOST_NODE_IP
              value: status.hostIP
            - name: MY_HOST_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_NAMESPACE
              value: {{ include "nuvlabox-engine.namespace" . }}
          ports:
            - containerPort: 80
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost/api/healthcheck
            initialDelaySeconds: 10
            periodSeconds: 30
          volumeMounts:
            - mountPath: /rootfs
              name: rootfs
              readOnly: true
            - mountPath: /srv/nuvlabox/shared
              name: nuvlabox-db


      ## VOLUMES
      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: nuvlabox-db
          hostPath:
            path: /var/lib/{{ include "nuvlabox-engine.namespace" . }}
