apiVersion: v1
kind: Service
metadata:
  name: agent
  namespace: {{ include "nuvlabox-engine.namespace" . }}
  labels:
    {{- include "nuvlabox-engine.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: True
  ports:
    - port: 80
      protocol: TCP
  selector:
    component: agent