---
apiVersion: v1
kind: Service
metadata:
  name: agent
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nuvlabox-engine.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    component: {{ .Values.coreComponentName }}

---
apiVersion: v1
kind: Service
metadata:
  name: system-manager
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nuvlabox-engine.labels" . | nindent 4 }}
spec:
  ports:
    - port: 3636
      protocol: TCP
  selector:
    component: {{ .Values.coreComponentName }}

---
apiVersion: v1
kind: Service
metadata:
  name: data-gateway
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nuvlabox-engine.labels" . | nindent 4 }}
spec:
  ports:
    - port: 1883
      protocol: TCP
  selector:
    component: {{ .Values.coreComponentName }}