---
apiVersion: v1
kind: Service
metadata:
  name: agent
  namespace: {{ include "nuvlabox-engine.namespace" . }}
  labels:
    {{- include "nuvlabox-engine.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: True
  ports:
    - port: 80
      protocol: TCP
  selector:
    component: {{ .Values.coreComponentName }}

---
apiVersion: v1
kind: Service
metadata:
  name: system-manager
  namespace: {{ include "nuvlabox-engine.namespace" . }}
  labels:
    {{- include "nuvlabox-engine.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: True
  ports:
    - port: 3636
      protocol: TCP
  selector:
    component: {{ .Values.coreComponentName }}

---
apiVersion: v1
kind: Service
metadata:
  name: data-gateway
  namespace: {{ include "nuvlabox-engine.namespace" . }}
  labels:
    {{- include "nuvlabox-engine.labels" . | nindent 4 }}
spec:
  publishNotReadyAddresses: True
  ports:
    - port: 1883
      targetPort: 1883
  selector:
    component: {{ .Values.coreComponentName }}

