---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuvlabox-engine-core-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nuvlabox-engine.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      component: nuvlabox-engine-core
  template:
    metadata:
      labels:
        component: nuvlabox-engine-core
        {{- include "nuvlabox-engine.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        # AGENT
        - name: agent
          image: "{{ .Values.images.agent.repository }}:{{ .Values.images.agent.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.agent.pullPolicy }}
          securityContext:
            privileged: true
          env:
            - name: NUVLABOX_UUID
              value: {{ .Values.NUVLABOX_UUID }}
            - name: NUVLABOX_ENGINE_VERSION
              value: "2.0.0"
            - name: NUVLABOX_IMMUTABLE_SSH_PUB_KEY
              value: {{ .Values.NUVLABOX_IMMUTABLE_SSH_PUB_KEY }}
            - name: NUVLA_ENDPOINT
              value: {{ .Values.NUVLA_ENDPOINT | default "nuvla.io" | quote }}
            - name: NUVLA_ENDPOINT_INSECURE
              value: {{ .Values.NUVLA_ENDPOINT_INSECURE | default "False" | quote }}
            - name: NUVLABOX_JOB_ENGINE_LITE_IMAGE
              value: "{{ .Values.images.jobEngineLite.repository }}:{{ .Values.images.jobEngineLite.tag }}"
            - name: NUVLABOX_VPN_COMPONENT_NAME
              value: {{ .Values.vpnClientComponentName }}
            - name: HOST_HOME
              value: {{ .Values.HOME }}
            - name: VPN_INTERFACE_NAME
              value: {{ .Values.VPN_INTERFACE_NAME | default "vpn" | quote }}
            - name: MY_HOST_NODE_IP
              value: status.hostIP
            - name: MY_HOST_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_NAMESPACE
              value: {{ .Values.namespace }}

        # K8S CREDENTIAL MANAGER
        - name: kubernetes-credentials-manager
          image: "{{ .Values.images.kubernetesCredentialsManager.repository }}:{{ .Values.images.kubernetesCredentialsManager.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.kubernetesCredentialsManager.pullPolicy }}

      volumes:
        - hostPath:
            path: /dev/net/tun
            type: CharDevice
          name: dev-tun

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-client-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nuvlabox-engine.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Values.vpnClientComponentName }}
  template:
    metadata:
      labels:
        component: {{ .Values.vpnClientComponentName }}
        {{- include "nuvlabox-engine.labels" . | nindent 8 }}
    spec:
      hostNetwork: true
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.vpnClientComponentName }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          image: "{{ .Values.images.vpnClient.repository }}:{{ .Values.images.vpnClient.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.vpnClient.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - ls
                - /dev/net/tun
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - mountPath: /dev/net/tun
              name: dev-tun
      volumes:
        - hostPath:
            path: /dev/net/tun
            type: CharDevice
          name: dev-tun