apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-credentials-manager-deployment
  namespace: {{ include "nuvlabox-engine.namespace" . }}
  labels:
    {{- include "nuvlabox-engine.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      component: kubernetes-credentials-manager
  template:
    metadata:
      labels:
        component: kubernetes-credentials-manager
        {{- include "nuvlabox-engine.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.kubernetesNode }}
      containers:
        - name: kubernetes-credentials-manager
          image: "{{ .Values.images.kubernetesCredentialsManager.repository }}:{{ .Values.images.kubernetesCredentialsManager.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.kubernetesCredentialsManager.pullPolicy }}
          volumeMounts:
            - mountPath: /srv/nuvlabox/shared
              name: nuvlabox-db

      ## VOLUMES
      volumes:
        - name: nuvlabox-db
          hostPath:
            path: /var/lib/{{ include "nuvlabox-engine.namespace" . }}
