{{- if .Values.peripheralManagerModbus }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peripheral-manager-modbus-deployment
  namespace: {{ include "nuvlabox-engine.namespace" . }}
  labels:
    {{- include "nuvlabox-engine.labels" . | nindent 4 }}
    {{- include "nuvlabox-engine.peripheral-manager.labels" . | nindent 4 }}
    nuvlabox.peripheral.type: modbus
spec:
  selector:
    matchLabels:
      component: peripheral-manager-modbus
  template:
    metadata:
      labels:
        component: peripheral-manager-modbus
        {{- include "nuvlabox-engine.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.kubernetesNode }}
      containers:
        - name: peripheral-manager-modbus
          image: "{{ .Values.images.peripheralManagerModbus.repository }}:{{ .Values.images.peripheralManagerModbus.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.peripheralManagerModbus.pullPolicy }}
          env:
            - name: MY_NAMESPACE
              value: {{ include "nuvlabox-engine.namespace" . }}
{{- end }}