{{- if .Values.peripheralManagerBluetooth }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peripheral-manager-bluetooth-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nuvlabox-engine.labels" . | nindent 4 }}
    {{- include "nuvlabox-engine.peripheral-manager.labels" . | nindent 4 }}
    nuvlabox.peripheral.type: bluetooth
spec:
  replicas: 1
  selector:
    matchLabels:
      component: peripheral-manager-bluetooth
  template:
    metadata:
      labels:
        component: peripheral-manager-bluetooth
        {{- include "nuvlabox-engine.labels" . | nindent 4 }}
    spec:
      hostNetwork: true
      containers:
        - name: peripheral-manager-bluetooth
          image: "{{ .Values.images.peripheralManagerBluetooth.repository }}:{{ .Values.images.peripheralManagerBluetooth.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.peripheralManagerBluetooth.pullPolicy }}
{{- end }}