apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-client-deployment
  labels:
    {{- include "nuvlabox-engine.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: vpn-client
  template:
    metadata:
      labels:
        component: vpn-client
    spec:
      restartPolicy: Always
      hostNetwork: true
      containers:
        - name: vpn-client
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          image: "{{ .Values.images.vpnClient.repository }}:{{ .Values.images.vpnClient.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.images.vpnClient.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - ls
                - /dev/net/tun
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - mountPath: /dev/net/tun
              name: dev-tun
      volumes:
        - hostPath:
            path: /dev/net/tun
            type: CharDevice
          name: dev-tun