version: "3.7"

x-common: &common
  image: ${DOCKER_ORG:-nuvlaedge}/nuvlaedge:${NUVLAEDGE_VERSION:-latest}
  stop_grace_period: 5s
  logging:
    options:
      max-size: "250k"
      max-file: "10"
  labels:
    - "nuvlaedge.component=True"
    - "nuvlaedge.deployment=production"
    - "nuvlaedge.peripheral.component=True"
    - "nuvlaedge.peripheral.type=modbus"


services:
  peripheral-manager-modbus:
    <<: *common
    entrypoint: modbus
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-peripheral-modbus
    restart: on-failure
    volumes:
      - nuvlabox-db:/srv/nuvlaedge/shared
    depends_on:
      - agent
