version: "3.7"

x-common: &common
  image: ${NE_IMAGE_REGISTRY:-}${NE_IMAGE_ORGANIZATION:-sixsq}/${NE_IMAGE_REPOSITORY:-nuvlaedge}:${NE_IMAGE_TAG:-2.14.3}
  stop_grace_period: 5s
  logging:
    options:
      max-size: "${LOG_MAX_SIZE:-250k}"
      max-file: "${LOG_MAX_FILE:-10}"
  labels:
    - "nuvlaedge.component=True"
    - "nuvlaedge.deployment=production"
    - "nuvlaedge.peripheral.component=True"
    - "nuvlaedge.peripheral.type=usb"
    - "nuvlaedge.module.name=usb"

services:
  peripheral-manager-usb:
    <<: *common
    entrypoint: usb
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-peripheral-usb
    network_mode: host
    environment:
      - NUVLAEDGE_LOG_LEVEL=${NUVLAEDGE_LOG_LEVEL:-INFO}
    volumes:
      - /dev:/dev:ro
      - /run/udev/control:/run/udev/control:ro
      - nuvlabox-db:/srv/nuvlaedge/shared
      - nuvlaedge-data:/var/lib/nuvlaedge
    depends_on:
      - agent
