version: "3.7"

x-common: &common
  image: ${DOCKER_ORG:-nuvlaedge}/nuvlaedge:${NUVLAEDGE_VERSION:-latest}
  stop_grace_period: 5s
  logging:
    options:
      max-size: "250k"
      max-file: "10"
  labels:
    - "nuvlaedge.component=True"
    - "nuvlaedge.deployment=production"
    - "nuvlaedge.peripheral.component=True"
    - "nuvlaedge.peripheral.type=gpu"

services:
  peripheral-manager-gpu:
    <<: *common
    entrypoint: gpu
    restart: on-failure
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-peripheral-gpu
    volumes:
      - /etc/:/etcfs/:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/lib/:/usr/lib/:ro
      - /dev/:/dev/:ro
      - nuvlabox-db:/srv/nuvlaedge/shared
    depends_on:
      - agent
