version: "3.7"

x-common: &common
  image: ${NE_IMAGE_REGISTRY:-}${NE_IMAGE_ORGANIZATION:-sixsq}/${NE_IMAGE_REPOSITORY:-nuvlaedge}:${NE_IMAGE_TAG:-2.10.1}
  stop_grace_period: 5s
  logging:
    options:
      max-size: "250k"
      max-file: "10"
  labels:
    - "nuvlaedge.component=True"
    - "nuvlaedge.deployment=production"
    - "nuvlaedge.peripheral.component=True"
    - "nuvlaedge.peripheral.type=gpu"

services:
  peripheral-manager-gpu:
    <<: *common
    entrypoint: gpu
    restart: on-failure
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-peripheral-gpu
    volumes:
      - nuvlabox-db:/srv/nuvlaedge/shared
      - /dev/:/host/dev/:ro
      - /etc/:/host/etc/:ro
      - /usr/lib/:/host/usr/lib/:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - agent
