version: "3.7"

x-common: &common
  image: ${NE_IMAGE_REGISTRY:-}${NE_IMAGE_ORGANIZATION:-sixsq}/${NE_IMAGE_REPOSITORY:-nuvlaedge}:${NE_IMAGE_TAG:-2.13.2}
  stop_grace_period: 5s
  logging:
    options:
      max-size: "${LOG_MAX_SIZE:-250k}"
      max-file: "${LOG_MAX_FILE:-10}"
  labels:
    - "nuvlaedge.component=True"
    - "nuvlaedge.deployment=production"
    - "nuvlaedge.peripheral.component=True"
    - "nuvlaedge.peripheral.type=gpu"
    - "nuvlaedge.module.name=gpu"

services:
  peripheral-manager-gpu:
    <<: *common
    entrypoint: gpu
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-peripheral-gpu
    environment:
      - NUVLAEDGE_LOG_LEVEL=${NUVLAEDGE_LOG_LEVEL:-INFO}
    volumes:
      - nuvlabox-db:/srv/nuvlaedge/shared
      - nuvlaedge-data:/var/lib/nuvlaedge
      - /dev/:/host/dev/:ro
      - /etc/:/host/etc/:ro
      - /usr/lib/:/host/usr/lib/:ro
      - ${DOCKER_SOCKET_PATH:-/var/run/docker.sock}:/var/run/docker.sock
    depends_on:
      - agent
