version: "3.7"

x-common: &common
  image: ${NE_IMAGE_REGISTRY:-}${NE_IMAGE_ORGANIZATION:-sixsq}/${NE_IMAGE_REPOSITORY:-nuvlaedge}:${NE_IMAGE_TAG:-2.11.1}
  stop_grace_period: 5s
  logging:
    options:
      max-size: "250k"
      max-file: "10"
  labels:
    - "nuvlaedge.component=True"
    - "nuvlaedge.deployment=production"
    - "nuvlaedge.peripheral.component=True"
    - "nuvlaedge.peripheral.type=bluetooth"
    - "nuvlaedge.module.name=bluetooth"

services:
  peripheral-manager-bluetooth:
    <<: *common
    entrypoint: bluetooth
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-peripheral-bluetooth
    network_mode: host
    volumes:
      - nuvlabox-db:/srv/nuvlaedge/shared
    depends_on:
      - agent
