version: "3.7"

x-common: &common
  image: ${NE_IMAGE_REGISTRY:-}${NE_IMAGE_ORGANIZATION:-sixsq}/${NE_IMAGE_REPOSITORY:-nuvlaedge}:${NE_IMAGE_TAG:-2.12.2}
  stop_grace_period: 5s
  logging:
    options:
      max-size: "250k"
      max-file: "10"
  labels:
    - "nuvlaedge.component=True"
    - "nuvlaedge.deployment=production"
    - "nuvlaedge.peripheral.component=True"
    - "nuvlaedge.peripheral.type=modbus"
    - "nuvlaedge.module.name=modbus"

services:
  peripheral-manager-modbus:
    <<: *common
    entrypoint: modbus
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-peripheral-modbus
    restart: unless-stopped
    environment:
      - NUVLAEDGE_LOG_LEVEL=${NUVLAEDGE_LOG_LEVEL:-INFO}
    volumes:
      - nuvlabox-db:/srv/nuvlaedge/shared
    depends_on:
      - agent
