version: "3.7"

x-common: &common
  image: ${NE_IMAGE_REGISTRY:-}${NE_IMAGE_ORGANIZATION:-sixsq}/${NE_IMAGE_REPOSITORY:-nuvlaedge}:${NE_IMAGE_TAG:-2.16.1}
  stop_grace_period: 5s
  logging:
    driver: "json-file"
    options:
      max-size: "${LOG_MAX_SIZE:-250k}"
      max-file: "${LOG_MAX_FILE:-10}"
  labels:
    - "nuvlaedge.component=True"
    - "nuvlaedge.deployment=production"
    - "nuvlaedge.peripheral.component=True"
    - "nuvlaedge.peripheral.type=bluetooth"
    - "nuvlaedge.module.name=bluetooth"

services:
  peripheral-manager-bluetooth:
    <<: *common
    entrypoint: bluetooth
    restart: unless-stopped
    container_name: ${COMPOSE_PROJECT_NAME:-nuvlaedge}-peripheral-bluetooth
    network_mode: host
    environment:
      - NUVLAEDGE_LOG_LEVEL=${NUVLAEDGE_LOG_LEVEL:-INFO}
    volumes:
      - nuvlaedge-data:/var/lib/nuvlaedge
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    depends_on:
      - agent
