{{- if .Values.peripheralManagerModbus }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peripheral-manager-modbus-deployment
  namespace: {{ include "nuvlaedge.namespace" . }}
  labels:
    {{- include "nuvlaedge.labels" . | nindent 4 }}
    {{- include "nuvlaedge.peripheral-manager.labels" . | nindent 4 }}
    nuvlaedge.peripheral.type: modbus
spec:
  selector:
    matchLabels:
      component: peripheral-manager-modbus
  template:
    metadata:
      labels:
        component: peripheral-manager-modbus
        {{- include "nuvlaedge.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.kubernetesNode }}
      containers:
        - name: peripheral-manager-modbus
          command: ["modbus"]
          image: "{{ .Values.nuvlaedge.image.registry }}{{ .Values.nuvlaedge.image.organization }}/{{ .Values.nuvlaedge.image.repository }}:{{ .Values.nuvlaedge.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nuvlaedge.pullPolicy }}
          env:
            - name: MY_NAMESPACE
              value: {{ include "nuvlaedge.namespace" . }}
{{- end }}
