{{- if .Values.peripheralManagerGPU }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peripheral-manager-gpu-deployment
  namespace: {{ include "nuvlaedge.namespace" . }}
  labels:
    {{- include "nuvlaedge.labels" . | nindent 4 }}
    {{- include "nuvlaedge.peripheral-manager.labels" . | nindent 4 }}
    nuvlaedge.peripheral.type: gpu
spec:
  selector:
    matchLabels:
      component: peripheral-manager-gpu
  template:
    metadata:
      labels:
        component: peripheral-manager-gpu
        {{- include "nuvlaedge.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.kubernetesNode }}
      {{- if .Values.allowControlPlane }}
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      {{- end }}
      containers:
        - name: peripheral-manager-gpu
          command: ["gpu"]
          image: "{{ .Values.nuvlaedge.image.registry }}{{ .Values.nuvlaedge.image.organization }}/{{ .Values.nuvlaedge.image.repository }}:{{ .Values.nuvlaedge.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nuvlaedge.pullPolicy }}
          volumeMounts:
            - mountPath: /var/lib/nuvlaedge
              name: nuvlaedge-data
            - mountPath: /host/dev
              name: dev
            - mountPath: /host/etc
              name: etc
              readOnly: true
            - mountPath: /host/usr/lib
              name: lib
              readOnly: true
          env:
            - name: MY_NAMESPACE
              value: {{ include "nuvlaedge.namespace" . }}
      volumes:
        - name: nuvlaedge-data
          hostPath:
            path: {{ .Values.nuvlaedgeVolumeHostPath }}/{{ include "nuvlaedge.namespace" . }}/data
        - hostPath:
            path: /dev
          name: dev
        - hostPath:
            path: /etc
          name: etc
        - hostPath:
            path: /usr/lib
          name: lib
{{- end }}
