{{- if .Values.peripheralManagerBluetooth }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peripheral-manager-bluetooth-deployment
  namespace: {{ include "nuvlaedge.namespace" . }}
  labels:
    {{- include "nuvlaedge.labels" . | nindent 4 }}
    {{- include "nuvlaedge.peripheral-manager.labels" . | nindent 4 }}
    nuvlaedge.peripheral.type: bluetooth
spec:
  selector:
    matchLabels:
      component: peripheral-manager-bluetooth
  template:
    metadata:
      labels:
        component: peripheral-manager-bluetooth
        {{- include "nuvlaedge.labels" . | nindent 8 }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.kubernetesNode }}
      containers:
        - name: peripheral-manager-bluetooth
          command: ["bluetooth"]
          image: "{{ .Values.nuvlaedge.image.registry }}{{ .Values.nuvlaedge.image.organization }}/{{ .Values.nuvlaedge.image.repository }}:{{ .Values.nuvlaedge.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nuvlaedge.pullPolicy }}
          env:
            - name: MY_NAMESPACE
              value: {{ include "nuvlaedge.namespace" . }}
          volumeMounts:
            - mountPath: /var/lib/nuvlaedge
              name: nuvlaedge-data
            - mountPath: /run/dbus/system_bus_socket
              name: dbus-socket
      volumes:
        - name: nuvlaedge-data
          hostPath:
            path: {{ .Values.nuvlaedgeVolumeHostPath }}/{{ include "nuvlaedge.namespace" . }}/data
        - name: dbus-socket
          hostPath:
            path: /run/dbus/system_bus_socket
{{- end }}
