apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # We've got a 63 character limit!
  name: nuvlaedge-service-account-cluster-role-binding-{{ include "nuvlaedge.uuid" .}}
  namespace: {{ include "nuvlaedge.namespace" . }}
  labels:
    {{- include "nuvlaedge.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nuvlaedge.serviceAccountName" . }}
    namespace: {{ include "nuvlaedge.namespace" . }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
