{{- if .Values.vpnClient }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpn-client
  namespace: {{ include "nuvlaedge.namespace" . }}
  labels:
    {{- include "nuvlaedge.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Values.vpnClientComponentName }}
  revisionHistoryLimit: {{ .Values.deploymentRevHistLimit }} 
  template:
    metadata:
      labels:
        component: {{ .Values.vpnClientComponentName }}
        {{- include "nuvlaedge.labels" . | nindent 8 }}
    spec:
      hostNetwork: true
      serviceAccountName: {{ .Values.serviceAccount.name }}
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.kubernetesNode }}
      containers:
        - name: {{ .Values.vpnClientComponentName }}
          command: ["openvpn-client"]
          image: "{{ .Values.nuvlaedge.image.registry }}{{ .Values.nuvlaedge.image.organization }}/{{ .Values.nuvlaedge.image.repository }}:{{ .Values.nuvlaedge.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nuvlaedge.pullPolicy }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          livenessProbe:
            exec:
              command:
                - ls
                - /dev/net/tun
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - mountPath: /dev/net/tun
              name: dev-tun
            - mountPath: /srv/nuvlaedge/shared
              name: nuvlaedge-db
            - mountPath: /var/lib/nuvlaedge
              name: nuvlaedge-data

      volumes:
        - name: dev-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: nuvlaedge-db
          hostPath:
            path: {{ .Values.nuvlaedgeVolumeHostPath }}/{{ include "nuvlaedge.namespace" . }}
        - name: nuvlaedge-data
          hostPath:
            path: {{ .Values.nuvlaedgeVolumeHostPath }}/{{ include "nuvlaedge.namespace" . }}/data
{{- end }}
