# Default values for nuvlaedge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

vpnClientComponentName: vpn-client

nuvlaedgeVolumeHostPath: /var/lib/nuvlaedge

nuvlaedge:
  image:
    registry: ""
    organization: sixsq
    repository: nuvlaedge
    #tag: "latest"
  dataGateway:
    repository: eclipse-mosquitto
    tag: "2.0.15-openssl"
  pullPolicy: Always

agentConfig:
  # comma separated list of monitors to exclude
  excluded_monitors:
  log_level: INFO

credManager:
  # name of the CertificateSigningRequest for the edge management credentials
  csr_name: nuvlaedge-csr
  # waiting time in seconds for approving the edge management credentials
  wait_approved_sec: 600
  # time to live after job finished
  ttlJobFinished: 5

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {"helm.sh/hook": "pre-install"}
  name: "nuvlaedge-service-account"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000


service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

tolerations: []

affinity: {}
