name: "NuvlaBox Functional Testing"

on:
  push:
    branches:
      - cicd
  # workflow_run:
  #   workflows: ["NuvlaBox Installer Build"]
  #   branches: [master]
  #   types:
  #     - completed

env:
  NUVLA_DEV_APIKEY: ${{ secrets.NUVLA_DEV_APIKEY }}
  NUVLA_DEV_APISECRET: ${{ secrets.NUVLA_DEV_APISECRET }}

jobs:
  tester:
    name: "Run NuvlaBox functional tests"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup dependencies
        run: |
          python --version
          pip --version
          sudo apt-get install -y python3-pytest
          cd test
          pip install -r requirements.txt
          docker swarm init

      - name: Preflight Checks
        run: |
          python -m pytest -vv -x --html=nuvlabox.pre-flight-check.output.html --self-contained-html pre-flight-check.py

      # - if: always()
      #   name: Keep test results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: pytest-report
      #     path: test/nuvlabox.e2e_pytest.output.html

      - name: Upload to slack step
        if: ${{ failure() }}
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: nuvlabox.pre-flight-check.output.html
          channel: nuvla-ci
          filetype: html
          filename: nuvlabox.pre-flight-check.output.html
          title: "NuvlaBox CI Preflight Check report"
          initial_comment: ":memo: HTML output from the automated NuvlaBox tests"

  notify:
    if: always()
    name: Post Workflow Status To Slack
    needs: tester
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          include_jobs: true
